### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by cferrarini** [alf45tar/Pedalino#1]
Hello friend

I would suggest you to use a display with i2c backpack, you can buy it apart, it uses only 2 wires.
Is it possible to use this library without the display? I want to make a simple minimalistic wired midi control for amplitube, with 5 momentary buttons and a bank switch to change 5 buttons between cc and pc, without bluetooth or wifi. Maybe a long press could change between cc and pc withou an extra button. Is it possible to do that?

**Comment by alf45tar** [comment]
I will add support for I2C display. Not a big deal because I have to change just one line of code.

My code is not a library but the firmware running on Pedalino hardware. Pedalino can run without display but you cannot change any parameter. Without display you can modify configuration changing the code ( I can support you) or connect a display just for change configuration. The new configuration will be saved into EEPROM and restored during boot.

If you don't need bluetooth and wifi just do not connect ESP8266/ESP32 board. No changes to software is required.

Pedalino support single press, double press and long press but right now cannot mix CC and PC on the same pedal. For example single press can send a CC value1, double press can send CC value2 and long press CC value3. As alternative single press can send PC value1, double press PC value2, and long press PC value3.

Different pedals can send different MIDI messages (CC, PC, notes, pitch bend) of course.

If not clear let me know.

Regards

**Comment by alf45tar** [comment]
I decided to move to the LCD Keypad Shield because it is very popular, cheap, easy to install and 5 buttons available.
